# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "QRL: The Quantum Resistant Ledger"
email: info@theqrl.org
description: > # this means to ignore newlines until "baseurl:"
  The Quantum Resistant Ledger
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://theqrl.org" # the base hostname & protocol for your site
social:
  youtube: https://www.youtube.com/c/QRLedger
  telegram: https://t.me/QRLedgerOfficial
  kakaotalk: https://open.kakao.com/o/gffKNhWb
collections:
  conferences:
    permalink: "/conferences/:year/:month/:slug/" 
    output: true
  faq:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
  roadmap:
    permalink: "/roadmap/:path/"
    output: true
  grants:
    permalink: "/grant/:path/"
    output: true
  team:
    permalink: "/:collection/:path/"
    output: false
  media:
    permalink: "/:collection/:path/"
    output: true
  qips:
    permalink: "/qip/:title/"
    output: true
defaults:
- scope:
   path: _team
  values:
    layout: human
- scope:
   path: _qips
  values:
    layout: qip
- scope:
   path: _media
  values:
    layout: media
- scope:
   path: _grants
  values:
    layout: grant
- scope:
    path: _roadmap
  values:
    layout: default
- scope:
    path: _conferences
  values:
    layout: conference
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
future: true
safe: false
plugins:
  - jekyll-sitemap
# Build settings
markdown: kramdown
theme: minima
