baseURL = "/"
languageCode = "en-us"
title = "QRL: The Quantum Resistant Ledger"
timeout = 300000


[params]
telegram="QRLedgerOfficial"
twitter="QRLedger"
youtube="QRLedger"
images = ["/logocircle.png"]
description = "The Quantum Resistant Ledger (QRL) is a first-of-its-kind, post-quantum value store and decentralized communication layer proactively tackling the threat advanced Quantum Computers pose to cryptocurrencies"


[module]
  [[module.imports]]
    path = 'github.com/theQRL/qips'
    diable = false

    [[module.imports.mounts]]
    source = './qips'
    target = 'content/qips'

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[taxonomies]
  author = "team"
  tag = "tags"
  category = "categories"
  feature = "features"
  fork = "forks"

[permalinks]
  "/blog/" = "/blog/:slug/"
  "/pages/" = "/:slug/"

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = true
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
