baseURL = "/"
languageCode = "en-us"
title = "QRL: The Quantum Resistant Ledger"
timeout = 300000

[params]
telegram="QRLedgerOfficial"
twitter="QRLedger"
youtube="QRLedger"
images = ["/logocircle.png"]
description = "The Quantum Resistant Ledger (QRL) is a first-of-its-kind, post-quantum value store and decentralized communication layer proactively tackling the threat advanced Quantum Computers pose to cryptocurrencies"
dateFormat = "02 Jan 2006"



[[headers]]
  for = '/**'
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-transform"
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "default-src 'self' 'unsafe-eval' *.youtube.com embed.typeform.com form.typeform.com; script-src 'self' *.googletagmanager.com embed.typeform.com *.google-analytics.com; media-src 'self' www.google-analytics.com *.youtube.com; font-src 'self' data:; frame-src 'self' *.youtube.com; connect-src 'self' *.google-analytics.com *.youtube.com; img-src 'self' *.google-analytics.com *.youtube.com; style-src 'self' 'unsafe-inline' embed.typeform.com; base-uri 'self'; frame-ancestors 'self' *.youtube.com; form-action 'self' theqrl.us15.list-manage.com; manifest-src 'self'; worker-src 'self';"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Permitted-Cross-Domain-Policies = "none"
    Cross-Origin-Embedder-Policy = "unsafe-none"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "cross-origin"

[module]
  [[module.imports]]
    path = 'github.com/theQRL/qips'
    disable = false

    [[module.imports.mounts]]
    source = './qips'
    target = 'content/qips'

  [[module.mounts]]
  source = 'assets/js/mathjax'
  target = 'static/js/mathjax'

  [[module.mounts]]
  source = 'assets/static'
  target = 'static'

  [[module.mounts]]
  source = 'assets/content/blog'
  target = 'static/img/blogs'

[markup]
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ''
    footnoteReturnLinkContents = ''
    fractions = true
    hrefTargetBlank = false
    latexDashes = false
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = false
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineAnchors = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4

[taxonomies]
author = "team"
tag = "tags"
category = "categories"
organization = "organizations"
nation = "nations"
feature = "features"
fork = "forks"
series = "series"
weekly = "weekly"
quantum-news = "quantum-news"

[permalinks]
blog = "/blog/:slug/"
events = "/events/:slug/"
pages = "/:slug/"
weekly = "/weekly/:slug/"
quantum = "/quantum/:year/:slug/"
organizations = "/quantum-news/organization/:slug"
nations = "/quantum-news/nation/:slug"


[minify]
  disableCSS = false
  disableHTML = false
  disableJS = true
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true

