baseURL = "/"
languageCode = "en-us"
title = "QRL: The Quantum Resistant Ledger"
timeout = 300000

[params]
telegram="QRLedgerOfficial"
twitter="QRLedger"
youtube="QRLedger"
images = ["/logocircle.png"]
description = "The Quantum Resistant Ledger (QRL) is a first-of-its-kind, post-quantum value store and decentralized communication layer proactively tackling the threat advanced Quantum Computers pose to cryptocurrencies"

[module]
  [[module.imports]]
    path = 'github.com/theQRL/qips'
    diable = false

    [[module.imports.mounts]]
    source = './qips'
    target = 'content/qips'

  [[module.mounts]]
  source = 'assets/js/mathjax'
  target = 'static/js/mathjax'

  [[module.mounts]]
  source = 'assets/static'
  target = 'static'

  [[module.mounts]]
  source = 'assets/content/blog'
  target = 'static/img/blogs'

[markup]
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ''
    footnoteReturnLinkContents = ''
    fractions = true
    hrefTargetBlank = false
    latexDashes = false
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = false
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineAnchors = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4

[taxonomies]
  author = "team"
  tag = "tags"
  category = "categories"
  feature = "features"
  fork = "forks"
  series = "series"

[permalinks]
  "/blog/" = "/blog/:slug/"
  "/pages/" = "/:slug/"

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = true
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
