[build]
publish = "public"

[build.processing]
skip_processing = true

[build.environment]
HUGO_VERSION = "0.97.3"

[context.production]
command = "hugo --gc --minify --baseURL $URL --buildFuture"

[context.deploy-preview]
command = "hugo --gc --minify --baseURL $DEPLOY_PRIME_URL --buildFuture"

[context.branch-deploy]
command = "hugo --gc --minify --baseURL $DEPLOY_PRIME_URL --buildFuture"