[build]
publish = "public"

[build.processing]
skip_processing = true

[build.environment]
HUGO_VERSION = "0.97.3"

[context.production]
command = "hugo --gc --minify -b $URL"

[context.deploy-preview]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
